---
title: "table"
author: "Xu Luo"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the package

```{r}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(knitr)
library(scales)
```

## Read the Data Set and filter children under 5
```{r}
health_all <- read.csv("2019-2020 NSCH_Topical_CAHMI_DRC_v1.2.csv")
health <- health_all %>% filter(SC_AGE_YEARS <= 5)

```


## EDA for independent variable: park_1920
```{r}
# EDA for park amenties.

num_with_park <- sum(health$park_1920 == "1")
num_without_park  <- sum(health$park_1920 == "2")
num_missing_park <- sum(health$park_1920 == "99")

park_ornot <- data.frame(
  group = c("YES", "NO", "MISSING"),
  count = c(num_with_park, num_without_park, num_missing_park)
  )
park_ornot

# calculate the percentage:
per_park <- park_ornot$count / sum(park_ornot$count)
per_park <- label_percent()(per_park)

park_ornot1 <- park_ornot %>%
  mutate(park_ornot, percentage = c(per_park))

kable(park_ornot1,caption = "Percentage Sumary")
```


## function
```{r}



single_table <- function(md){
mt <- tibble(md)
ans <- mt %>% count(md)%>%arrange() %>% mutate(propotion = n / sum(n))
return(ans)
}

#test on park
single_table(health$park_1920)
```






























































































































