---
title: "Titiana"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Enviroment

```{r}
# Library(???)
library(readr)
library(likert)
library(ggplot2)
library(xtable)
library(dplyr)
library(ggplot2)
library(stringr)
```

```{r}

NSCH <- read_csv("NSCH1920.csv")

NSCH <- subset(NSCH,SC_AGE_YEARS <=5)
NSCH <- subset(NSCH, K4Q27 != 99)

YES <- subset(NSCH,K4Q27 == 1)
NO <- subset(NSCH,K4Q27 == 2)
```
```{r}
y <- NSCH$K4Q27
unique(NSCH$K4Q27)

length(which(y == 99))

# 1 "Did not receive needed health care"
# 2 "Received needed health care (or did not need health care)"
# 99 "Missing".
```


#Plot1 - parent educ
```{r}
edu <- NSCH$AdultEduc_1920
# 1 "Less than high school"
# 2 "High school or GED"
# 3 "Some college or technical school"
# 4 "College degree or higher"

sex <- NSCH$sex_1920
# 1 "Male"
# 2 "Female"

md1 <- data.frame(y,edu,sex)

```



```{r}
md11 <- subset(md1,y ==1)
md12 <- subset(md1,y ==2)

n <- nrow(md11)

edu_1_1 = length(which(md11$edu == 1))/n
edu_1_2 = length(which(md11$edu == 2))/n
edu_1_3 = length(which(md11$edu == 3))/n
edu_1_4 = length(which(md11$edu == 4))/n

edu_1_total = c(edu_1_1,edu_1_2,edu_1_3,edu_1_4)
edu_1_name = c("Less than high school","High school or GED","Some college or technical school","College degree or higher")

data <- data.frame(
  group=edu_1_name,
  value=edu_1_total
)

# piechart
ggplot(data, aes(x="", y=value, fill=group)) +
  ggtitle("Did not receive needed health care")+
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0)+
  scale_fill_brewer(palette="Set2")
```

```{r}
n <- nrow(md12)

edu_2_1 = length(which(md12$edu == 1))/n
edu_2_2 = length(which(md12$edu == 2))/n
edu_2_3 = length(which(md12$edu == 3))/n
edu_2_4 = length(which(md12$edu == 4))/n

edu_2_total = c(edu_2_1,edu_2_2,edu_2_3,edu_2_4)
edu_2_name = c("Less than high school","High school or GED","Some college or technical school","College degree or higher")

data <- data.frame(
  group=edu_2_name,
  value=edu_2_total
)

# piechart
ggplot(data, aes(x="", y=value, fill=group)) +
  ggtitle("Received needed health care (or did not need health care)")+
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0)+
  scale_fill_brewer(palette="Set3")
```


```{r}
# alternative pie chart
# Compute the position of labels
data <- data %>% 
  arrange(desc(group)) %>%
  mutate(prop = value / sum(data$value) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )

# Basic piechart
ggplot(data, aes(x="", y=prop, fill=group)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme(legend.position="none") +
  
  geom_text(aes(y = ypos, label = group), color = "black", size=3) +
  scale_fill_brewer(palette="Set3")
```



Description & Interpretation:



#Plot2
```{r}

park <- NSCH$park_1920
#Children who live in neighborhoods with a park or playground
# 1 "Yes"
# 2 "No"
RecCentr <- NSCH$RecCentr_1920
#Children who live in neighborhoods with recreation center, community center or boys’ and girls’ club
# 1 "Yes"
# 2 "No"
library <- NSCH$library_1920
#Children who live in neighborhoods with a library or bookmobile
# 1 "Yes"
# 2 "No"
NbhdAmenities <- NSCH$NbhdAmenities_1920
#Indicator 7.4: Count of amenities in children's neighborhoods
# 0 "Neighborhood does not contain any amenities" 
# 1 "Neighborhood contains 1 amenity"
# 2 "Neighborhood contains 2 amenities"
# 3 "Neighborhood contains 3 amenities"
# 4 "Neighborhood contains all 4 amenities"

md2 <- data.frame(y,park,RecCentr,library,NbhdAmenities)

```


```{r}
# drop all missing values
missing <-unique(which(md2[,2:5] == 99))
md2<-md2[-missing,]

```

```{r}

no2 <- subset(md2,y == 2)-1
yes2 <- subset(md2,y == 1)-1
```

```{r}
value<-1:6

value[1] = 1-sum(yes2$park)/nrow(yes2)
value[2] = 1-sum(no2$park)/nrow(no2)

value[3] = 1-sum(yes2$RecCentr)/nrow(yes2)
value[4] = 1-sum(no2$RecCentr)/nrow(no2)

value[5] = 1-sum(yes2$library)/nrow(yes2)
value[6] = 1-sum(no2$library)/nrow(no2)
```




```{r}
# create a dataset
Public_Utilities <- c(rep("park" , 2) , rep("library" , 2) , rep("recreation center" , 2) )
Group <- rep(c("Received" , "Not Receive") , 3)
Ratio <- value
data <- data.frame(Public_Utilities,Group,Ratio)
# Grouped
ggplot(data, aes(fill=Group, y=Ratio, x=Public_Utilities)) + 
    geom_bar(position="dodge", stat="identity")
```

Description & Interpretation:



#Plot3

```{r}
# hike_data <- readr::read_rds(url('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-24/hIke_data.rds'))
hike_data$region <- as.factor(word(hike_data$location, 1, sep = " -- "))
hike_data$length_num <- as.numeric(sapply(strsplit(hike_data$length, " "), "[[", 1))

plot_df <- hike_data %>%
  group_by(region) %>%
  summarise(
    sum_length = sum(length_num),
    mean_gain = mean(as.numeric(gain)),
    n = n()
  ) %>%
  mutate(mean_gain = round(mean_gain, digits = 0))


plt <- plt +
  # Annotate the bars and the lollipops so the reader understands the scaling
  annotate(
    x = 11, 
    y = 1300,
    label = "Mean Elevation Gain\n[FASL]",
    geom = "text",
    angle = -67.5,
    color = "gray12",
    size = 2.5,
    family = "Bell MT"
  ) +
  annotate(
    x = 11, 
    y = 3150,
    label = "Cummulative Length [FT]",
    geom = "text",
    angle = 23,
    color = "gray12",
    size = 2.5,
    family = "Bell MT"
  ) +
  # Annotate custom scale inside plot
  annotate(
    x = 11.7, 
    y = 1100, 
    label = "1000", 
    geom = "text", 
    color = "gray12", 
    family = "Bell MT"
  ) +
  annotate(
    x = 11.7, 
    y = 2100, 
    label = "2000", 
    geom = "text", 
    color = "gray12", 
    family = "Bell MT"
  ) +
  annotate(
    x = 11.7, 
    y =3100, 
    label = "3000", 
    geom = "text", 
    color = "gray12", 
    family = "Bell MT"
  ) +
  # Scale y axis so bars don't start in the center
  scale_y_continuous(
    limits = c(-1500, 3500),
    expand = c(0, 0),
    breaks = c(0, 1000, 2000, 3000)
  ) + 
  # New fill and legend title for number of tracks per region
  scale_fill_gradientn(
    "Amount of Tracks",
     colours = c( "#6C5B7B","#C06C84","#F67280","#F8B195")
  ) +
  # Make the guide for the fill discrete
  guides(
    fill = guide_colorsteps(
      barwidth = 15, barheight = .5, title.position = "top", title.hjust = .5
    )
  ) +
  theme(
    # Remove axis ticks and text
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    # Use gray text for the region names
    axis.text.x = element_text(color = "gray12", size = 12),
    # Move the legend to the bottom
    legend.position = "bottom",
  )

plt

```


```{r}
plt <- ggplot(plot_df) +
  # Make custom panel grid
  geom_hline(
    aes(yintercept = y), 
    data.frame(y = c(0:3) * 1000),
    color = "lightgrey"
  ) + 
  # Add bars to represent the cumulative track lengths
  # str_wrap(region, 5) wraps the text so each line has at most 5 characters
  # (but it doesn't break long words!)
  geom_col(
    aes(
      x = reorder(str_wrap(region, 5), sum_length),
      y = sum_length,
      fill = n
    ),
    position = "dodge2",
    show.legend = TRUE,
    alpha = .9
  ) +
  
  # Add dots to represent the mean gain
  geom_point(
    aes(
      x = reorder(str_wrap(region, 5),sum_length),
      y = mean_gain
    ),
    size = 3,
    color = "gray12"
  ) +
  
  # Lollipop shaft for mean gain per region
  geom_segment(
    aes(
      x = reorder(str_wrap(region, 5), sum_length),
      y = 0,
      xend = reorder(str_wrap(region, 5), sum_length),
      yend = 3000
    ),
    linetype = "dashed",
    color = "gray12"
  ) + 
  
  # Make it circular!
  coord_polar()

plt
```


Description & Interpretation:



#Plot4


```{r}

get_prop <- function(vec){
  mc <- vec
  mdex <- which(mc == 99)
  w <- mc[-mdex]
  w = w-1
  p = 1-sum(w)/length(w)
  return(p)
}


ydeaf <- YES$K2Q43B
ndeaf <- NO$K2Q43B

yblind <- YES$BLINDNESS
nblind <- NO$BLINDNESS

yars<- YES$ARTHRITIS
nars <- NO$ARTHRITIS

yasthma<- YES$K2Q40A
nasthma <- NO$K2Q40A


ydiabetes<- YES$K2Q41A
ndiabetes <- NO$K2Q41A


cont <- c(get_prop(ydeaf),get_prop(ndeaf),
          get_prop(yblind),get_prop(nblind),
          get_prop(yars),get_prop(nars),
          get_prop(yasthma),get_prop(nasthma),
          get_prop(ydiabetes),get_prop(ndiabetes)) # bycol

 
# Create data: note in High school for several students
data <- as.data.frame(matrix( cont , ncol=5,byrow = FALSE))
colnames(data) <- c("deaf" , "blind" , "Arthritis" , "Asthma" , "Diabetes" )
rownames(data) <- c("a" , "b")

```

```{r}
data = data*100

data
```



```{r,warning=FALSE}
# Library
library(fmsb)

 
# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each variable to show on the plot!
data <- rbind(rep(12,5) , rep(0,5) , data)
 
# Set graphic colors
library(RColorBrewer)
coul <- brewer.pal(3, "BuPu")
colors_border <- coul
library(scales)
colors_in <- alpha(coul,0.3)

# If you remove the 2 first lines, the function compute the max and min of each variable with the available data:
radarchart( data[-c(1,2),]  , axistype=0 , maxmin=F,
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
    #custom the grid
    cglcol="red", cglty=1, axislabcol="grey", cglwd=0.8, 
    #custom labels
    vlcex=0.8 
    )

# Add a legend
legend(x=0.7, y=1, legend = rownames(data[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "black", cex=1.2, pt.cex=3)

```
```{r}

# Custom the radarChart !
radarchart( data  , axistype=1 , 
 
    #custom polygon
    pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5) , plwd=4 , 
 
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
 
    #custom labels
    vlcex=0.8 
    )
```





Description & Interpretation:



#Plot5
```{r}

```

Description & Interpretation:



#Plot6
```{r}

```

Description & Interpretation:



































